# Generated by Django 4.2.11 on 2024-03-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mhbdips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "contact_method",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")], max_length=5
                    ),
                ),
                (
                    "best_time",
                    models.CharField(
                        choices=[("am", "AM"), ("pm", "PM")], max_length=2
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
    ]
