# Generated by Django 4.2.11 on 2024-03-27 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mhbdips", "0002_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
