# Generated by Django 4.2.11 on 2024-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mhbdips", "0003_product_favorites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="zipcode",
            field=models.IntegerField(default=0),
        ),
    ]
