# Generated by Django 4.2.11 on 2024-04-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mhbdips", "0004_alter_orderdetail_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="address",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="shipper",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mhbdips.shipper",
            ),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="state",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="zipcode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
