# Generated by Django 4.2.11 on 2024-04-14 17:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mhbdips", "0006_accounts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Accounts",
            new_name="Account",
        ),
    ]
