# Generated by Django 4.2.11 on 2024-04-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mhbdips", "0007_rename_accounts_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="order_images/"),
        ),
    ]
